from flask import render_template, request
from . import bp
import os
import json

@bp.route('/test')
def test():
    """Test route that returns just TEST text."""
    return "TEST"

@bp.route('/panels')
def panels():
    """Render the LLM panels."""
    post_id = request.args.get('post_id')
    substage = request.args.get('substage', 'idea')
    
    if not post_id:
        return "Post ID is required", 400
        
    # Load configuration from planning_steps.json
    config_path = os.path.join(os.path.dirname(__file__), 'config', 'planning_steps.json')
    with open(config_path, 'r') as f:
        planning_steps = json.load(f)
    
    # Get the configuration for the current substage
    step_config = planning_steps['planning']['idea']['initial']
    
    # Example input/output values
    input_values = {
        'idea_seed': 'This is a sample initial idea for testing the panel.'
    }
    
    output_values = {
        'expanded_idea': 'This is a sample expanded idea that would be generated by the LLM.'
    }
        
    return render_template('panel.html', 
        step_config=step_config,
        input_values=input_values,
        output_values=output_values,
        substage=substage,
        post={'id': post_id}
    ) 