from flask import render_template, request
from . import bp

@bp.route('/test')
def test():
    """Test route that returns just TEST text."""
    return "TEST"

@bp.route('/panels')
def panels():
    """Render the LLM panels."""
    post_id = request.args.get('post_id')
    substage = request.args.get('substage', 'idea')
    
    if not post_id:
        return "Post ID is required", 400
        
    # Example step configuration - this should come from your database
    step_config = {
        'inputs': {
            'idea_seed': {
                'type': 'textarea',
                'db_field': 'idea_seed',
                'db_table': 'post_development'
            }
        },
        'outputs': {
            'expanded_idea': {
                'type': 'textarea',
                'db_field': 'expanded_idea',
                'db_table': 'post_development'
            }
        },
        'settings': {
            'llm': {
                'model': 'mistral',
                'task_prompt': 'Expand the initial idea into a more detailed concept.',
                'input_mapping': {
                    'idea_seed': 'idea_seed'
                },
                'parameters': {
                    'temperature': 0.7,
                    'max_tokens': 1000,
                    'top_p': 1.0,
                    'frequency_penalty': 0.0,
                    'presence_penalty': 0.0
                }
            }
        }
    }
    
    # Example input/output values
    input_values = {
        'idea_seed': 'This is a sample initial idea for testing the panel.'
    }
    
    output_values = {
        'expanded_idea': 'This is a sample expanded idea that would be generated by the LLM.'
    }
        
    return render_template('panel.html', 
        step_config=step_config,
        input_values=input_values,
        output_values=output_values,
        substage=substage,
        post={'id': post_id}
    ) 