"""Add autoincrement to Post id

Revision ID: 12508c133a42
Revises: 42e71b8ed909
Create Date: 2025-04-24 14:24:25.925203

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "12508c133a42"
down_revision = "42e71b8ed909"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_constraint("post_author_id_fkey", type_="foreignkey")
        batch_op.drop_column("author_id")

    op.drop_table("user")

    # Create sequence for post id if it doesn't exist
    op.execute("CREATE SEQUENCE IF NOT EXISTS post_id_seq")
    op.execute("ALTER TABLE post ALTER COLUMN id SET DEFAULT nextval('post_id_seq')")
    op.execute("ALTER SEQUENCE post_id_seq OWNED BY post.id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.create_foreign_key(
            "post_author_id_fkey", "user", ["author_id"], ["id"]
        )

    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column(
            "password_hash", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="user_pkey"),
        sa.UniqueConstraint("email", name="user_email_key"),
        sa.UniqueConstraint("username", name="user_username_key"),
    )
    # ### end Alembic commands ###
