"""Remove basic_idea and concept from Post model, migrate to workflow_status.stage_data only

Revision ID: 3856d3f55261
Revises: 9e81edb1fdb4
Create Date: 2025-04-26 14:25:10.202790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3856d3f55261'
down_revision = '9e81edb1fdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('basic_idea')
        batch_op.drop_column('concept')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concept', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('basic_idea', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
