"""Add post_id to Image model

Revision ID: 4c7057d5438b
Revises: f07d8b8521a4
Create Date: 2025-04-24 07:11:43.957017

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c7057d5438b"
down_revision = "f07d8b8521a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.add_column(sa.Column("post_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_image_post_id", "post", ["post_id"], ["id"], ondelete="CASCADE"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.drop_constraint("fk_image_post_id", type_="foreignkey")
        batch_op.drop_column("post_id")
    # ### end Alembic commands ###
