"""Add subtitle field to post

Revision ID: a494479e5ce4
Revises: post_section_enhancements
Create Date: 2025-04-23 13:08:17.612262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a494479e5ce4'
down_revision = 'post_section_enhancements'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
