-- Add quirky news classification and image fields to newsletter_source_item
-- Phase 2.1: Database Schema Extensions

BEGIN;

ALTER TABLE newsletter_source_item
ADD COLUMN IF NOT EXISTS heuristic_score NUMERIC(8,3) DEFAULT 0,
ADD COLUMN IF NOT EXISTS heuristic_flags JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS llm_class VARCHAR(32),  -- quirky|not_quirky|uncertain
ADD COLUMN IF NOT EXISTS llm_quirky_score INTEGER,  -- 0-100
ADD COLUMN IF NOT EXISTS llm_summary_raw TEXT,
ADD COLUMN IF NOT EXISTS safety_flag VARCHAR(32),  -- none|death|serious_illness|crime|other
ADD COLUMN IF NOT EXISTS selected_for_highlights BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS available_images JSONB DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_nsi_heuristic_score ON newsletter_source_item(heuristic_score) WHERE heuristic_score > 0;
CREATE INDEX IF NOT EXISTS idx_nsi_llm_class ON newsletter_source_item(llm_class) WHERE llm_class IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_nsi_safety_flag ON newsletter_source_item(safety_flag) WHERE safety_flag IS NOT NULL;

COMMENT ON COLUMN newsletter_source_item.heuristic_score IS 'Pre-LLM filtering score based on keywords and sections';
COMMENT ON COLUMN newsletter_source_item.heuristic_flags IS 'Array of keywords/sections that contributed to heuristic score';
COMMENT ON COLUMN newsletter_source_item.llm_class IS 'LLM classification: quirky, not_quirky, or uncertain';
COMMENT ON COLUMN newsletter_source_item.llm_quirky_score IS 'LLM-assigned quirky score from 0-100';
COMMENT ON COLUMN newsletter_source_item.llm_summary_raw IS 'Neutral summary generated by LLM';
COMMENT ON COLUMN newsletter_source_item.safety_flag IS 'Safety classification for sensitive content';
COMMENT ON COLUMN newsletter_source_item.selected_for_highlights IS 'Whether this article has been selected for weekly highlights';
COMMENT ON COLUMN newsletter_source_item.available_images IS 'Array of available images with captions and credits';

COMMIT;

