"""Remove source_field from LLMAction model

Revision ID: 41f6b3209b58
Revises: 738c9a32a531
Create Date: 2025-05-02 11:58:00.578667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f6b3209b58'
down_revision = '738c9a32a531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_action', schema=None) as batch_op:
        batch_op.drop_column('source_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_field', sa.VARCHAR(length=128), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
