"""Service for interacting with LLM providers."""

import httpx
import logging
import re
from flask import current_app
from datetime import datetime
from jinja2 import Template
import psycopg2
import psycopg2.extras

logger = logging.getLogger(__name__)
# All ORM model imports removed. Use direct SQL via psycopg2 for any DB access.

def execute_llm_request(request_data):
    """Execute an LLM request with the given parameters."""
    try:
        service = LLMService()
        
        # Log the incoming request
        logger.info(f"Executing LLM request with data: {request_data}")
        
        # Get the prompt and input
        prompt_template = request_data.get('prompt', '').strip()
        input_text = request_data.get('input', '').strip()
        
        # Strip [system] and similar tags from prompt
        cleaned_prompt = re.sub(r'\[.*?\]', '', prompt_template).strip()
        
        # Format the prompt in a clear, explicit way
        prompt = f"""{cleaned_prompt}

Input: {input_text}"""

        logger.debug(f"Using formatted prompt: {prompt}")
        
        # Generate the output
        output = service.generate(
            prompt,
            model_name=request_data['model_name'],
            temperature=request_data.get('temperature', 0.7),
            max_tokens=request_data.get('max_tokens', 2000)
        )
        
        if not output:
            logger.error("LLM service returned empty output")
            return {'error': 'No output generated by the LLM service'}
            
        logger.info(f"Successfully generated output")
        
        # Return in the format expected by the frontend
        return {
            'model_used': request_data['model_name'],
            'response': output
        }
        
    except Exception as e:
        logger.exception(f"Error executing LLM request: {str(e)}")
        return {'error': str(e)}

def assemble_prompt_from_parts(action, fields: dict):
    """
    Assemble a prompt or message list from all prompt parts for an action, ordered.
    For OpenAI: returns a list of {role, content} dicts.
    For Ollama: returns a single concatenated string.
    """
    prompt_parts = (
        LLMActionPromptPart.query.filter_by(action_id=action['id'])
        .order_by(LLMActionPromptPart.order)
        .all()
    )
    messages = []
    for part_link in prompt_parts:
        part = part_link.prompt_part
        # Render with Jinja2
        try:
            content = Template(part.content).render(**fields)
        except Exception as e:
            logger.error(f"Error rendering prompt part {part.id}: {e}")
            content = part.content
        # For OpenAI, use role; for Ollama, just concatenate
        if part.type in ('system', 'user', 'assistant'):
            messages.append({'role': part.type, 'content': content})
        else:
            # For style/instructions/other, treat as user message
            messages.append({'role': 'user', 'content': content})
    # For Ollama, concatenate all content
    ollama_prompt = '\n\n'.join([m['content'] for m in messages])
    return {'openai': messages, 'ollama': ollama_prompt}

def parse_tagged_prompt_to_messages(prompt_template: str, fields: dict) -> dict:
    """
    Parse a tagged prompt template into structured messages (for chat LLMs) and a canonical prompt string (for single-prompt LLMs).
    Returns: { 'messages': [...], 'prompt': '...' }
    """
    current_app.logger.debug(f"[DEBUG] Parsing tagged prompt: {prompt_template}")
    # Replace [data:FIELDNAME] with the actual input, if present
    def replace_data_tags(text):
        def repl(match):
            key = match.group(1)
            return str(fields.get(key, f"[{key}]") if fields else f"[{key}]")
        return re.sub(r'\[data:([a-zA-Z0-9_]+)\]', repl, text)

    # Find all [role: TAG] or [role] blocks
    tag_pattern = re.compile(r'\[(system|user|assistant)(?::\s*([A-Z_]+))?\]\s*([^\[]+)', re.IGNORECASE)
    matches = tag_pattern.findall(prompt_template)
    current_app.logger.debug(f"[DEBUG] Tag matches: {matches}")
    # Group content by role
    role_contents = {'system': [], 'user': [], 'assistant': []}
    for role, tag, content in matches:
        role = role.lower()
        content = replace_data_tags(content.strip())
        role_contents.setdefault(role, []).append(content)
    # Compose messages for chat LLMs
    messages = []
    for role in ('system', 'user', 'assistant'):
        if role_contents[role]:
            messages.append({'role': role, 'content': ' '.join(role_contents[role])})
    # Compose canonical prompt string for single-prompt LLMs
    prompt_lines = []
    if role_contents['system']:
        prompt_lines.append(' '.join(role_contents['system']))
    if role_contents['user']:
        prompt_lines.append('Task: ' + ' '.join(role_contents['user']))
    if 'input' in fields:
        prompt_lines.append('Input: ' + str(fields['input']))
    prompt = '\n'.join(prompt_lines)
    current_app.logger.debug(f"[DEBUG] Parsed messages: {messages}")
    current_app.logger.debug(f"[DEBUG] Parsed prompt: {prompt}")
    return {'messages': messages, 'prompt': prompt}

def modular_prompt_to_canonical(prompt_json, fields: dict) -> dict:
    """
    Convert a modular prompt array (list of parts) and runtime fields into a canonical prompt string and message list.
    Returns: { 'messages': [...], 'prompt': '...' }
    """
    # If string, parse as JSON
    import json as _json
    if isinstance(prompt_json, str):
        try:
            prompt_json = _json.loads(prompt_json)
        except Exception:
            return {'messages': [], 'prompt': ''}
    # If already canonical object, treat as one-part modular
    if isinstance(prompt_json, dict):
        prompt_json = [prompt_json]
    # Compose canonical fields
    role = ''
    voice = ''
    operation = ''
    data = ''
    system_lines = []
    user_lines = []
    for part in prompt_json:
        tags = [t.lower() for t in part.get('tags', [])]
        content = part.get('content', '')
        if 'role' in tags:
            role = content
            system_lines.append(content)
        elif 'style' in tags or 'voice' in tags:
            voice = content
            system_lines.append(content)
        elif 'operation' in tags:
            operation = content
            user_lines.append(content)
        elif 'data' in tags or part.get('type') == 'data':
            data = content
    # Compose canonical prompt string
    prompt_lines = []
    if system_lines:
        prompt_lines.append(' '.join(system_lines))
    if user_lines:
        prompt_lines.append('Task: ' + ' '.join(user_lines))
    # Insert runtime input if present
    input_val = fields.get('input') or data
    if input_val:
        prompt_lines.append('Input: ' + str(input_val))
    prompt = '\n'.join(prompt_lines)
    # Compose messages for chat LLMs
    messages = []
    if system_lines:
        messages.append({'role': 'system', 'content': ' '.join(system_lines)})
    if user_lines:
        messages.append({'role': 'user', 'content': ' '.join(user_lines)})
    if input_val:
        messages.append({'role': 'user', 'content': str(input_val)})
    return {'messages': messages, 'prompt': prompt}

class LLMService:
    """Service for interacting with LLM providers."""

    def __init__(self):
        """Initialize the LLM service."""
        self.config = None  # provider type (e.g., 'ollama', 'openai')
        self.api_url = None  # provider API URL

    def generate(self, prompt, model_name=None, temperature=0.7, max_tokens=1000):
        """Generate text using configured LLM, supporting both OpenAI (messages) and Ollama (string)."""
        if not model_name:
            model_name = self.config
        logger.info(f"Generating with model: {model_name}, temperature: {temperature}, max_tokens: {max_tokens}")
        if self.config == "ollama":
            return self._generate_ollama(prompt, model_name, temperature, max_tokens)
        elif self.config == "openai":
            return self._generate_openai(prompt, model_name, temperature, max_tokens)
        else:
            raise ValueError(f"Unsupported provider type: {self.config}")

    def _generate_ollama(self, prompt, model_name, temperature=0.7, max_tokens=1000):
        """Generate text using Ollama."""
        try:
            # Format request JSON consistently
            request_data = {
                "model": model_name,
                "prompt": prompt,
                "temperature": float(temperature),  # Ensure temperature is float
                "max_tokens": int(max_tokens),      # Ensure max_tokens is int
                "stream": False  # Ensure we get a complete response
            }
            logger.debug(f"Sending request to Ollama: {request_data}")
            if not self.api_url:
                raise ValueError("Ollama API URL not set on LLMService")
            response = httpx.post(
                f"{self.api_url}/api/generate",
                json=request_data,
                timeout=180.0,
            )
            response.raise_for_status()
            response_data = response.json()
            logger.debug(f"Received response from Ollama: {response_data}")
            # Handle both response formats
            if "response" in response_data:
                return response_data["response"]
            elif isinstance(response_data, dict) and "model_used" in response_data and "response" in response_data:
                return response_data["response"]
            else:
                logger.error(f"Unexpected response format from Ollama: {response_data}")
                raise ValueError("Unexpected response format from Ollama")
        except httpx.TimeoutException:
            logger.error(f"Timeout while generating with Ollama (model: {model_name})")
            raise TimeoutError("Request to Ollama timed out")
        except httpx.HTTPError as e:
            logger.error(f"HTTP error while generating with Ollama: {str(e)}")
            raise
        except Exception as e:
            logger.exception(f"Error generating with Ollama: {str(e)}")
            raise

    def _generate_openai(self, prompt, model_name, temperature=0.7, max_tokens=1000):
        """Generate text using OpenAI (stubbed for testing)."""
        # Return a dummy response for testing if no API key is set
        return "[DUMMY OPENAI RESPONSE]"

    def execute_action(self, action, fields: dict, post_id=None, model_name=None):
        model = None
        if model_name:
            model = model_name
        elif action['llm_model']:
            model = action['llm_model']
        else:
            raise ValueError(f"LLM model not set on action {action['id']}")
        # Use self.config and self.api_url as set by the caller.
        # --- NEW: Transform modular prompt_json to canonical prompt/messages ---
        prompt_json = action.get('prompt_json')
        parsed = modular_prompt_to_canonical(prompt_json, fields)
        current_app.logger.debug(f"[DEBUG] LLMService.execute_action parsed: {parsed}")
        input_field = action.get('input_field') or 'input'
        output_field = action.get('output_field') or 'output'
        if self.config == 'openai':
            result = self.generate(parsed['messages'], model_name=model, temperature=action['temperature'], max_tokens=action['max_tokens'])
        elif self.config == 'ollama':
            result = self.generate(parsed['prompt'], model_name=model, temperature=action['temperature'], max_tokens=action['max_tokens'])
        else:
            raise ValueError(f"Unsupported provider type: {self.config}")
        if isinstance(result, dict) and 'output' in result:
            result = {output_field: result['output'], **{k: v for k, v in result.items() if k != 'output'}}
        elif isinstance(result, str):
            result = {output_field: result}
        def make_json_safe(obj):
            if isinstance(obj, dict):
                return {k: make_json_safe(v) for k, v in obj.items()}
            elif isinstance(obj, list):
                return [make_json_safe(i) for i in obj]
            return obj
        return make_json_safe(result)

# Remove all ORM model usage below, stub out as needed for migration. 